//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunity
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> Customer_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public string Categary { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string HowFound { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> EstCloseDate { get; set; }
        public Nullable<int> Probabilities { get; set; }
        public Nullable<decimal> EstRevenue { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
